execute pathogen#infect()
syntax on
filetype plugin indent on

set nu
syntax enable

"暂时不清楚作用的

filetype plugin on
set softtabstop =2
set shiftwidth=2
autocmd FileType c set tabstop=4
autocmd FileType javascript set tabstop=2

"暂时不需要的
"设置不兼容
"set nocompatible
"语言
"let $lang = 'en'
"set langmenu=en
"language message 'en'
"Tab键的宽度
"autocmd FileType c set tabstop=4
"autocmd FileType javascript set tabstop=2
"统一缩进为2
"set softtabstop=2
"set shiftwidth=2
"空格代替制表符
"set noexpandtab

"set expandtab
"在行和段开始处使用制表符
"set smarttab
"禁止生成临时文件
"set nobackup
"set noswapfile
"搜索忽略大小写
"set ingorecase
"上下行始终保持2行
"set scrolloff=2
"行距
"set linespacce=0
"允许折叠
"set foldenable
"手动折叠
"set foldmethod=manual
"
"""""""""""""""""""""""""""""""""""""""自有设置更改 Begin"""""""""""""""""""""""""""""""""""""""""""""""
"selonsy 2016年7月12日09:29:18

"自动缩进
set autoindent
set cindent

"编码设置
set guifont=Consolas:h13:cANSI
set encoding=utf-8
"set fileencoding=utf-8,chinese
set termencoding=utf-8
if has("win32")
  set fileencoding=chinese
else
  set fileencoding=utf-8
endif

"处理菜单及右键菜单乱码
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim

"处理console输出乱码
language messages zh_CN.utf-8

"backspace键不能使用的问题
set backspace=indent,eol,start

"设置窗口大小
set lines=50 columns=150
"设定窗口位置
winpos 500 0

"用浅色高亮当前行
set cursorline
set cursorcolumn

"自动缩进
autocmd InsertLeave * se nocul
autocmd InsertLeave * se cul

"设置背景
set background=dark

"设置配色方案
colorscheme solarized

"不要图形按钮
set go=

"切换主题
call togglebg#map("<F5>")

"搜索逐字符高亮
set hlsearch
set incsearch

"更改方向键
"map <UP> <NOP>
"map <DOWN> <NOP>
"map <LEFT> <NOP>
"map <RIGHT> <NOP>
"inoremap <UP> <NOP>
"inoremap <DOWN> <NOP>
"inoremap <LEFT> <NOP>
"inoremap <RIGHT> <NOP>

"字典文件
au FileType javascript set dictionary+=$HOME/.vim/dict/node.dict

""""""""""""""""""""""""""""""""""""""自有设置更改 End"""""""""""""""""""""""""""""""""""""""""""""""

""""""""""""""""""""""""""""""""""""""插件配置区 Begin"""""""""""""""""""""""""""""""""""""""""""""""

"nerd tree 树形结构
nmap <F12> :NERDTreeToggle<cr>

"syntastic 语法检查
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

"CtrlP 全局文件查找
"set wildignore+=*/tmp/*,*.so,*.swp,*.zip          " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe,*.tmp  " Windows
let g:ctrlp_custom_ignore = {
    \ 'dir':  '\v[\/]\.(git|hg|svn|rvm)$',
    \ 'file': '\v\.(exe|so|dll|zip|tar|tar.gz|pyc)$',
    \ }

"let g:ctrlp_user_command = 'find %s -type f'        " MacOSX/Linux
let g:ctrlp_user_command = 'dir %s /-n /b /s /a-d'  " Windows
let g:ctrlp_working_path_mode = 'c'
"let g:ctrlp_working_path_mode=0
let g:ctrlp_show_hidden=0
let g:ctrlp_match_window_bottom=1
let g:ctrlp_max_height=15
let g:ctrlp_match_window_reversed=0
let g:ctrlp_mruf_max=500
let g:ctrlp_follow_symlinks=1
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
""""""""""""""""""""""""""""""""""""""插件配置区 End""""""""""""""""""""""""""""""""""""""""""""""""""








